name: interactive_cv
description: "A Flutter app that presents my professional profile, skills, and experience interactively."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: 2.6.1

  # Routing
  go_router: 13.2.0

  # HTTP & API
  dio: 5.9.0

  # Models & Serialization
  freezed_annotation: 2.4.1
  json_annotation: 4.7.0

  # Utilities
  url_launcher: 6.1.11
  share_plus: 7.2.2
  flutter_local_notifications: 17.2.4
  intl: 0.18.1

  # UI Icons
  cupertino_icons: 1.0.6
  
  # UI Helpers
  lottie: 2.3.2
  flutter_svg: 1.1.6
  cached_network_image: 3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  flutter_lints: 2.0.1
  analyzer: 5.6.0
  build_runner: 2.3.3
  freezed: 2.3.3
  json_serializable: 6.5.4

flutter:

  uses-material-design: true

  assets:
     - assets/images/
  